name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: node_modules/.bin/nyc --reporter=clover node_modules/.bin/mocha --color --forbid-only "test/**/*.test.ts"
      - name: Upload to CodeCov
        run: bash <(curl -s https://codecov.io/bash)
